#!/usr/bin/env bash

PORT=4000
ENTRYPOINT="dev.php"

# Configure the PHP server to start two
# concurrent threads.
export PHP_CLI_SERVER_WORKERS=2

serve() {
  php -S 0.0.0.0:$PORT $ENTRYPOINT
}

deploy() {
  # The deployment on the old shared hosting uses a git clone that we need to update.
  echo 'h obliviously.eu && git pull && git submodule update' | ssh s11

  # The new deployments on the {du}punkto server use normal FTP/SCP uploads.
  lift deploy
}